/* Automatically generated by './build/build-components-entry.js' */

import { default as MazArrowIcon } from './MazArrowIcon.js'
import { default as MazAvatar } from './MazAvatar.js'
import { default as MazBackDrop } from './MazBackDrop.js'
import { default as MazBadge } from './MazBadge.js'
import { default as MazBottomSheet } from './MazBottomSheet.js'
import { default as MazBtn } from './MazBtn.js'
import { default as MazCard } from './MazCard.js'
import { default as MazCarousel } from './MazCarousel.js'
import { default as MazChart } from './MazChart.js'
import { default as MazCheckbox } from './MazCheckbox.js'
import { default as MazDialog } from './MazDialog.js'
import { default as MazDialogPromise } from './MazDialogPromise.js'
import { default as MazDrawer } from './MazDrawer.js'
import { default as MazDropzone } from './MazDropzone.js'
import { default as MazGallery } from './MazGallery.js'
import { default as MazIcon } from './MazIcon.js'
import { default as MazInput } from './MazInput.js'
import { default as MazInputNumber } from './MazInputNumber.js'
import { default as MazInputPrice } from './MazInputPrice.js'
import { default as MazInputTags } from './MazInputTags.js'
import { default as MazLazyImg } from './MazLazyImg.js'
import { default as MazPhoneNumberInput } from './MazPhoneNumberInput.js'
import { default as MazPicker } from './MazPicker.js'
import { default as MazRadioButtons } from './MazRadioButtons.js'
import { default as MazSelect } from './MazSelect.js'
import { default as MazSlider } from './MazSlider.js'
import { default as MazSpinner } from './MazSpinner.js'
import { default as MazSwitch } from './MazSwitch.js'
import { default as MazTabsBar } from './MazTabsBar.js'
import { default as MazTabsContent } from './MazTabsContent.js'
import { default as MazTabsContentItem } from './MazTabsContentItem.js'
import { default as MazTransitionExpand } from './MazTransitionExpand.js'

export {
  MazArrowIcon,
  MazAvatar,
  MazBackDrop,
  MazBadge,
  MazBottomSheet,
  MazBtn,
  MazCard,
  MazCarousel,
  MazChart,
  MazCheckbox,
  MazDialog,
  MazDialogPromise,
  MazDrawer,
  MazDropzone,
  MazGallery,
  MazIcon,
  MazInput,
  MazInputNumber,
  MazInputPrice,
  MazInputTags,
  MazLazyImg,
  MazPhoneNumberInput,
  MazPicker,
  MazRadioButtons,
  MazSelect,
  MazSlider,
  MazSpinner,
  MazSwitch,
  MazTabsBar,
  MazTabsContent,
  MazTabsContentItem,
  MazTransitionExpand
}

export default {
  MazArrowIcon,
  MazAvatar,
  MazBackDrop,
  MazBadge,
  MazBottomSheet,
  MazBtn,
  MazCard,
  MazCarousel,
  MazChart,
  MazCheckbox,
  MazDialog,
  MazDialogPromise,
  MazDrawer,
  MazDropzone,
  MazGallery,
  MazIcon,
  MazInput,
  MazInputNumber,
  MazInputPrice,
  MazInputTags,
  MazLazyImg,
  MazPhoneNumberInput,
  MazPicker,
  MazRadioButtons,
  MazSelect,
  MazSlider,
  MazSpinner,
  MazSwitch,
  MazTabsBar,
  MazTabsContent,
  MazTabsContentItem,
  MazTransitionExpand
}
