name: Doc Build and Deploy
on:
  push:

jobs:
  doc-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install all dependencies
        run: npm i

      - name: Build docs
        run: npm run docs:build

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          TARGET_REPO: LouisMazel/vuepress-test
          TARGET_BRANCH: gh-pages
          BUILD_DIR: docs/.vuepress/dist
